// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegerBiblioteca.Infra.Persistence;

#nullable disable

namespace RegerBiblioteca.Infra.Persistence.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20250620190151_SeedLivros")]
    partial class SeedLivros
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RegerBiblioteca.Core.Entities.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Biografia")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFalecimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nacionalidade")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SiteUrl")
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Autor", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biografia = "Autora da série Harry Potter.",
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5586),
                            DataNascimento = new DateTime(1965, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoUrl = "https://example.com/jk_rowling.jpg",
                            Nacionalidade = "Britânica",
                            Nome = "J.K. Rowling",
                            SiteUrl = "https://www.jkrowling.com/"
                        },
                        new
                        {
                            Id = 2,
                            Biografia = "Autor da série As Crônicas de Gelo e Fogo.",
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5593),
                            DataNascimento = new DateTime(1948, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoUrl = "https://example.com/george_rr_martin.jpg",
                            Nacionalidade = "Americano",
                            Nome = "George R.R. Martin",
                            SiteUrl = "https://www.georgerrmartin.com/"
                        },
                        new
                        {
                            Id = 3,
                            Biografia = "Rainha do crime, famosa por seus romances policiais.",
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5596),
                            DataFalecimento = new DateTime(1976, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1890, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoUrl = "https://example.com/agatha_christie.jpg",
                            Nacionalidade = "Britânica",
                            Nome = "Agatha Christie",
                            SiteUrl = "https://www.agathachristie.com/"
                        },
                        new
                        {
                            Id = 4,
                            Biografia = "Mestre do terror moderno, autor de O Iluminado.",
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5598),
                            DataNascimento = new DateTime(1947, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoUrl = "https://example.com/stephen_king.jpg",
                            Nacionalidade = "Americano",
                            Nome = "Stephen King",
                            SiteUrl = "https://www.stephenking.com/"
                        },
                        new
                        {
                            Id = 5,
                            Biografia = "Pioneiro da ficção científica, criador das Três Leis da Robótica.",
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5600),
                            DataFalecimento = new DateTime(1992, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1920, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoUrl = "https://example.com/isaac_asimov.jpg",
                            Nacionalidade = "Americano",
                            Nome = "Isaac Asimov",
                            SiteUrl = "https://asimovonline.com/"
                        },
                        new
                        {
                            Id = 6,
                            Biografia = "Autora clássica de romances como Orgulho e Preconceito.",
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5602),
                            DataFalecimento = new DateTime(1817, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1775, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoUrl = "https://example.com/jane_austen.jpg",
                            Nacionalidade = "Britânica",
                            Nome = "Jane Austen",
                            SiteUrl = "https://www.janeausten.org/"
                        },
                        new
                        {
                            Id = 7,
                            Biografia = "Autor de thrillers como O Código Da Vinci.",
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5604),
                            DataNascimento = new DateTime(1964, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoUrl = "https://example.com/dan_brown.jpg",
                            Nacionalidade = "Americano",
                            Nome = "Dan Brown",
                            SiteUrl = "https://danbrown.com/"
                        },
                        new
                        {
                            Id = 8,
                            Biografia = "Historiador e autor de Sapiens: Uma Breve História da Humanidade.",
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5605),
                            DataNascimento = new DateTime(1976, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoUrl = "https://example.com/yuval_harari.jpg",
                            Nacionalidade = "Israelense",
                            Nome = "Yuval Noah Harari",
                            SiteUrl = "https://www.ynharari.com/"
                        },
                        new
                        {
                            Id = 9,
                            Biografia = "Uma das maiores escritoras brasileiras, conhecida por sua prosa introspectiva.",
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5607),
                            DataFalecimento = new DateTime(1977, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1920, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoUrl = "https://example.com/clarice_lispector.jpg",
                            Nacionalidade = "Brasileira",
                            Nome = "Clarice Lispector",
                            SiteUrl = "https://claricelispector.ims.com.br/"
                        },
                        new
                        {
                            Id = 10,
                            Biografia = "Considerado o maior escritor brasileiro, autor de Dom Casmurro.",
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5609),
                            DataFalecimento = new DateTime(1908, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1839, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoUrl = "https://example.com/machado_de_assis.jpg",
                            Nacionalidade = "Brasileiro",
                            Nome = "Machado de Assis",
                            SiteUrl = "https://machadodeassis.net/"
                        });
                });

            modelBuilder.Entity("RegerBiblioteca.Core.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5156),
                            Descricao = "Histórias centradas em relacionamentos amorosos, com foco nas emoções e desenvolvimento dos personagens.",
                            Genero = 1,
                            Nome = "Romance"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5174),
                            Descricao = "Envolve mundos imaginários, magia, criaturas místicas e heróis épicos. Ex: O Senhor dos Anéis.",
                            Genero = 1,
                            Nome = "Fantasia"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5176),
                            Descricao = "Explora futuros possíveis, tecnologia avançada, vida em outros planetas, inteligência artificial, etc.",
                            Genero = 1,
                            Nome = "Ficção Científica"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5177),
                            Descricao = "Visa provocar medo ou tensão. Pode incluir elementos sobrenaturais, psicológicos ou monstros.",
                            Genero = 1,
                            Nome = "Terror/Horror"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5179),
                            Descricao = "Narrativas cheias de tensão e mistério, com reviravoltas e sensação de perigo constante.",
                            Genero = 1,
                            Nome = "Suspense/Thriller"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5216),
                            Descricao = "Histórias com exploração, ação e desafios físicos ou geográficos. Muitas vezes envolvem viagens e descobertas.",
                            Genero = 1,
                            Nome = "Aventura"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5218),
                            Descricao = "Gira em torno de investigações, assassinatos ou crimes, com detetives, policiais ou investigadores.",
                            Genero = 1,
                            Nome = "Policial/Crime"
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5219),
                            Descricao = "Mostra sociedades futuristas \"perfeitas\" (utopias) ou opressoras e disfuncionais (distopias). Ex: 1984, Admirável Mundo Novo.",
                            Genero = 1,
                            Nome = "Distopia/Utopia"
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5221),
                            Descricao = "Foca em dilemas humanos, conflitos emocionais e desenvolvimento pessoal.",
                            Genero = 1,
                            Nome = "Drama"
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5222),
                            Descricao = "Escrita para crianças e adolescentes, muitas vezes com lições morais e linguagem acessível.",
                            Genero = 1,
                            Nome = "Literatura Infantojuvenil"
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5223),
                            Descricao = "Histórias da vida real de pessoas (biografias escritas por terceiros ou autobiografias escritas pelo próprio autor).",
                            Genero = 2,
                            Nome = "Biografia/Autobiografia"
                        },
                        new
                        {
                            Id = 12,
                            Ativo = true,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5224),
                            Descricao = "Oferece conselhos e reflexões para melhorar aspectos da vida pessoal, emocional ou profissional.",
                            Genero = 2,
                            Nome = "Autoajuda/Desenvolvimento Pessoal"
                        },
                        new
                        {
                            Id = 13,
                            Ativo = true,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5225),
                            Descricao = "Relatos e análises sobre eventos históricos, períodos ou civilizações.",
                            Genero = 2,
                            Nome = "História"
                        },
                        new
                        {
                            Id = 14,
                            Ativo = true,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5226),
                            Descricao = "Explicações e explorações sobre o mundo natural, física, biologia, astronomia, etc.",
                            Genero = 2,
                            Nome = "Ciência"
                        },
                        new
                        {
                            Id = 15,
                            Ativo = true,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5228),
                            Descricao = "Discute questões existenciais, éticas, morais e o pensamento humano ao longo da história.",
                            Genero = 2,
                            Nome = "Filosofia"
                        },
                        new
                        {
                            Id = 16,
                            Ativo = true,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5229),
                            Descricao = "Explora crenças, tradições religiosas, textos sagrados e espiritualidade em geral.",
                            Genero = 2,
                            Nome = "Religião/Espiritualidade"
                        },
                        new
                        {
                            Id = 17,
                            Ativo = true,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5230),
                            Descricao = "Foca em empreendedorismo, mercado financeiro, administração e carreiras.",
                            Genero = 2,
                            Nome = "Negócios/Economia"
                        },
                        new
                        {
                            Id = 18,
                            Ativo = true,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5231),
                            Descricao = "Livros para aprendizado de matérias escolares, técnicas ou idioma",
                            Genero = 2,
                            Nome = "Educação/Didáticos"
                        },
                        new
                        {
                            Id = 19,
                            Ativo = true,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5232),
                            Descricao = "Receitas, técnicas de cozinha e cultura alimentar.",
                            Genero = 2,
                            Nome = "Culinária/Gastronomia"
                        },
                        new
                        {
                            Id = 20,
                            Ativo = true,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5233),
                            Descricao = "Relatos de experiências em outros países, guias turísticos e dicas de roteiros.",
                            Genero = 2,
                            Nome = "Viagens"
                        });
                });

            modelBuilder.Entity("RegerBiblioteca.Core.Entities.Emprestimo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataDevolucao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEmprestimo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExemplarId")
                        .HasColumnType("int");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExemplarId");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Emprestimo", (string)null);
                });

            modelBuilder.Entity("RegerBiblioteca.Core.Entities.Exemplar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CodigoBarras")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstadoConservacao")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("LivroId")
                        .HasColumnType("int");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.ToTable("Exemplar", (string)null);
                });

            modelBuilder.Entity("RegerBiblioteca.Core.Entities.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataDemissao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Funcionario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cargo = "Administrador",
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5425),
                            DataAdmissao = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@exemplo.com",
                            Matricula = "12345",
                            Nome = "Admin",
                            Senha = "****"
                        });
                });

            modelBuilder.Entity("RegerBiblioteca.Core.Entities.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoPublicacao")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Livro", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnoPublicacao = 1997,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5640),
                            ISBN = "978-8532511010",
                            Titulo = "Harry Potter e a Pedra Filosofal"
                        },
                        new
                        {
                            Id = 2,
                            AnoPublicacao = 1996,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5643),
                            ISBN = "978-8576572001",
                            Titulo = "As Crônicas de Gelo e Fogo: A Guerra dos Tronos"
                        },
                        new
                        {
                            Id = 3,
                            AnoPublicacao = 1934,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5644),
                            ISBN = "978-8501401600",
                            Titulo = "Assassinato no Expresso do Oriente"
                        },
                        new
                        {
                            Id = 4,
                            AnoPublicacao = 1977,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5646),
                            ISBN = "978-8551001007",
                            Titulo = "O Iluminado"
                        },
                        new
                        {
                            Id = 5,
                            AnoPublicacao = 1950,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5647),
                            ISBN = "978-8532523037",
                            Titulo = "Eu, Robô"
                        },
                        new
                        {
                            Id = 6,
                            AnoPublicacao = 1813,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5649),
                            ISBN = "978-8503012262",
                            Titulo = "Orgulho e Preconceito"
                        },
                        new
                        {
                            Id = 7,
                            AnoPublicacao = 2003,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5650),
                            ISBN = "978-8575422391",
                            Titulo = "O Código Da Vinci"
                        },
                        new
                        {
                            Id = 8,
                            AnoPublicacao = 2011,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5652),
                            ISBN = "978-8535925197",
                            Titulo = "Sapiens: Uma Breve História da Humanidade"
                        });
                });

            modelBuilder.Entity("RegerBiblioteca.Core.Entities.LivroAutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("LivroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("LivroId");

                    b.ToTable("LivroAutor", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutorId = 1,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5677),
                            LivroId = 1
                        },
                        new
                        {
                            Id = 2,
                            AutorId = 2,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5679),
                            LivroId = 2
                        },
                        new
                        {
                            Id = 3,
                            AutorId = 3,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5679),
                            LivroId = 3
                        },
                        new
                        {
                            Id = 4,
                            AutorId = 4,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5680),
                            LivroId = 4
                        },
                        new
                        {
                            Id = 5,
                            AutorId = 5,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5681),
                            LivroId = 5
                        },
                        new
                        {
                            Id = 6,
                            AutorId = 6,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5731),
                            LivroId = 6
                        },
                        new
                        {
                            Id = 7,
                            AutorId = 7,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5733),
                            LivroId = 7
                        },
                        new
                        {
                            Id = 8,
                            AutorId = 8,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5734),
                            LivroId = 8
                        });
                });

            modelBuilder.Entity("RegerBiblioteca.Core.Entities.LivroCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("LivroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("LivroId");

                    b.ToTable("LivroCategoria", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 2,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5762),
                            LivroId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5764),
                            LivroId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 7,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5765),
                            LivroId = 3
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 4,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5766),
                            LivroId = 4
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 3,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5767),
                            LivroId = 5
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 1,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5768),
                            LivroId = 6
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 5,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5769),
                            LivroId = 7
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 13,
                            CriadoEm = new DateTime(2025, 6, 20, 16, 1, 50, 628, DateTimeKind.Local).AddTicks(5769),
                            LivroId = 8
                        });
                });

            modelBuilder.Entity("RegerBiblioteca.Core.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("RegerBiblioteca.Core.Entities.Emprestimo", b =>
                {
                    b.HasOne("RegerBiblioteca.Core.Entities.Exemplar", "Exemplar")
                        .WithMany()
                        .HasForeignKey("ExemplarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegerBiblioteca.Core.Entities.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegerBiblioteca.Core.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exemplar");

                    b.Navigation("Funcionario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RegerBiblioteca.Core.Entities.Exemplar", b =>
                {
                    b.HasOne("RegerBiblioteca.Core.Entities.Livro", "Livro")
                        .WithMany("Exemplares")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("RegerBiblioteca.Core.Entities.LivroAutor", b =>
                {
                    b.HasOne("RegerBiblioteca.Core.Entities.Autor", "Autor")
                        .WithMany("Livros")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegerBiblioteca.Core.Entities.Livro", "Livro")
                        .WithMany("Autores")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("RegerBiblioteca.Core.Entities.LivroCategoria", b =>
                {
                    b.HasOne("RegerBiblioteca.Core.Entities.Categoria", "Categoria")
                        .WithMany("Livros")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegerBiblioteca.Core.Entities.Livro", "Livro")
                        .WithMany("Categorias")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("RegerBiblioteca.Core.Entities.Autor", b =>
                {
                    b.Navigation("Livros");
                });

            modelBuilder.Entity("RegerBiblioteca.Core.Entities.Categoria", b =>
                {
                    b.Navigation("Livros");
                });

            modelBuilder.Entity("RegerBiblioteca.Core.Entities.Livro", b =>
                {
                    b.Navigation("Autores");

                    b.Navigation("Categorias");

                    b.Navigation("Exemplares");
                });
#pragma warning restore 612, 618
        }
    }
}
